//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ProductList", Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
[System.Xml.Serialization.XmlRootAttribute("Products", Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01", IsNullable=false)]
public partial class ProductList1 {
    
    private ProductType[] productField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public ProductType[] Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
[System.Xml.Serialization.XmlRootAttribute("Product", Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01", IsNullable=false)]
public partial class ProductType {
    
    private IdentifierType identifiersField;
    
    private AttributeSetType[] attributeSetsField;
    
    private BaseRelationshipType[] relationshipsField;
    
    private CompetitivePricingType competitivePricingField;
    
    private SalesRankType[] salesRankingsField;
    
    private LowestOfferListingType[] lowestOfferListingsField;
    
    private OfferType[] offersField;
    
    /// <remarks/>
    public IdentifierType Identifiers {
        get {
            return this.identifiersField;
        }
        set {
            this.identifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AttributeSet", IsNullable=false)]
    public AttributeSetType[] AttributeSets {
        get {
            return this.attributeSetsField;
        }
        set {
            this.attributeSetsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BaseRelationship", IsNullable=false)]
    public BaseRelationshipType[] Relationships {
        get {
            return this.relationshipsField;
        }
        set {
            this.relationshipsField = value;
        }
    }
    
    /// <remarks/>
    public CompetitivePricingType CompetitivePricing {
        get {
            return this.competitivePricingField;
        }
        set {
            this.competitivePricingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SalesRank", IsNullable=false)]
    public SalesRankType[] SalesRankings {
        get {
            return this.salesRankingsField;
        }
        set {
            this.salesRankingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LowestOfferListing", IsNullable=false)]
    public LowestOfferListingType[] LowestOfferListings {
        get {
            return this.lowestOfferListingsField;
        }
        set {
            this.lowestOfferListingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Offer", IsNullable=false)]
    public OfferType[] Offers {
        get {
            return this.offersField;
        }
        set {
            this.offersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
[System.Xml.Serialization.XmlRootAttribute("Identifiers", Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01", IsNullable=false)]
public partial class IdentifierType {
    
    private MarketplaceASINType marketplaceASINField;
    
    private SellerSKUIdentifier sKUIdentifierField;
    
    /// <remarks/>
    public MarketplaceASINType MarketplaceASIN {
        get {
            return this.marketplaceASINField;
        }
        set {
            this.marketplaceASINField = value;
        }
    }
    
    /// <remarks/>
    public SellerSKUIdentifier SKUIdentifier {
        get {
            return this.sKUIdentifierField;
        }
        set {
            this.sKUIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class MarketplaceASINType {
    
    private string marketplaceIdField;
    
    private string aSINField;
    
    /// <remarks/>
    public string MarketplaceId {
        get {
            return this.marketplaceIdField;
        }
        set {
            this.marketplaceIdField = value;
        }
    }
    
    /// <remarks/>
    public string ASIN {
        get {
            return this.aSINField;
        }
        set {
            this.aSINField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class ShippingTimeType {
    
    private string maxField;
    
    /// <remarks/>
    public string Max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class QualifiersType {
    
    private string itemConditionField;
    
    private string itemSubconditionField;
    
    private string fulfillmentChannelField;
    
    private string shipsDomesticallyField;
    
    private ShippingTimeType shippingTimeField;
    
    private string sellerPositiveFeedbackRatingField;
    
    /// <remarks/>
    public string ItemCondition {
        get {
            return this.itemConditionField;
        }
        set {
            this.itemConditionField = value;
        }
    }
    
    /// <remarks/>
    public string ItemSubcondition {
        get {
            return this.itemSubconditionField;
        }
        set {
            this.itemSubconditionField = value;
        }
    }
    
    /// <remarks/>
    public string FulfillmentChannel {
        get {
            return this.fulfillmentChannelField;
        }
        set {
            this.fulfillmentChannelField = value;
        }
    }
    
    /// <remarks/>
    public string ShipsDomestically {
        get {
            return this.shipsDomesticallyField;
        }
        set {
            this.shipsDomesticallyField = value;
        }
    }
    
    /// <remarks/>
    public ShippingTimeType ShippingTime {
        get {
            return this.shippingTimeField;
        }
        set {
            this.shippingTimeField = value;
        }
    }
    
    /// <remarks/>
    public string SellerPositiveFeedbackRating {
        get {
            return this.sellerPositiveFeedbackRatingField;
        }
        set {
            this.sellerPositiveFeedbackRatingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class LowestOfferListingType {
    
    private QualifiersType qualifiersField;
    
    private string numberOfOfferListingsConsideredField;
    
    private string sellerFeedbackCountField;
    
    private PriceType priceField;
    
    private string multipleOffersAtLowestPriceField;
    
    /// <remarks/>
    public QualifiersType Qualifiers {
        get {
            return this.qualifiersField;
        }
        set {
            this.qualifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumberOfOfferListingsConsidered {
        get {
            return this.numberOfOfferListingsConsideredField;
        }
        set {
            this.numberOfOfferListingsConsideredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SellerFeedbackCount {
        get {
            return this.sellerFeedbackCountField;
        }
        set {
            this.sellerFeedbackCountField = value;
        }
    }
    
    /// <remarks/>
    public PriceType Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string MultipleOffersAtLowestPrice {
        get {
            return this.multipleOffersAtLowestPriceField;
        }
        set {
            this.multipleOffersAtLowestPriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class PriceType {
    
    private MoneyType landedPriceField;
    
    private MoneyType listingPriceField;
    
    private MoneyType shippingField;
    
    /// <remarks/>
    public MoneyType LandedPrice {
        get {
            return this.landedPriceField;
        }
        set {
            this.landedPriceField = value;
        }
    }
    
    /// <remarks/>
    public MoneyType ListingPrice {
        get {
            return this.listingPriceField;
        }
        set {
            this.listingPriceField = value;
        }
    }
    
    /// <remarks/>
    public MoneyType Shipping {
        get {
            return this.shippingField;
        }
        set {
            this.shippingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class MoneyType {
    
    private string currencyCodeField;
    
    private decimal amountField;
    
    private bool amountFieldSpecified;
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmountSpecified {
        get {
            return this.amountFieldSpecified;
        }
        set {
            this.amountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class SalesRankType {
    
    private string productCategoryIdField;
    
    private string rankField;
    
    /// <remarks/>
    public string ProductCategoryId {
        get {
            return this.productCategoryIdField;
        }
        set {
            this.productCategoryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class OfferType {
    
    private PriceType buyingPriceField;
    
    private MoneyType regularPriceField;
    
    private string fulfillmentChannelField;
    
    private string itemConditionField;
    
    private string itemSubConditionField;
    
    private string sellerIdField;
    
    private string sellerSKUField;
    
    /// <remarks/>
    public PriceType BuyingPrice {
        get {
            return this.buyingPriceField;
        }
        set {
            this.buyingPriceField = value;
        }
    }
    
    /// <remarks/>
    public MoneyType RegularPrice {
        get {
            return this.regularPriceField;
        }
        set {
            this.regularPriceField = value;
        }
    }
    
    /// <remarks/>
    public string FulfillmentChannel {
        get {
            return this.fulfillmentChannelField;
        }
        set {
            this.fulfillmentChannelField = value;
        }
    }
    
    /// <remarks/>
    public string ItemCondition {
        get {
            return this.itemConditionField;
        }
        set {
            this.itemConditionField = value;
        }
    }
    
    /// <remarks/>
    public string ItemSubCondition {
        get {
            return this.itemSubConditionField;
        }
        set {
            this.itemSubConditionField = value;
        }
    }
    
    /// <remarks/>
    public string SellerId {
        get {
            return this.sellerIdField;
        }
        set {
            this.sellerIdField = value;
        }
    }
    
    /// <remarks/>
    public string SellerSKU {
        get {
            return this.sellerSKUField;
        }
        set {
            this.sellerSKUField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class OfferListingCountType {
    
    private string conditionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class CompetitivePriceType {
    
    private string competitivePriceIdField;
    
    private PriceType priceField;
    
    private string conditionField;
    
    private string subconditionField;
    
    private bool belongsToRequesterField;
    
    /// <remarks/>
    public string CompetitivePriceId {
        get {
            return this.competitivePriceIdField;
        }
        set {
            this.competitivePriceIdField = value;
        }
    }
    
    /// <remarks/>
    public PriceType Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string condition {
        get {
            return this.conditionField;
        }
        set {
            this.conditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subcondition {
        get {
            return this.subconditionField;
        }
        set {
            this.subconditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool belongsToRequester {
        get {
            return this.belongsToRequesterField;
        }
        set {
            this.belongsToRequesterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class CompetitivePricingType {
    
    private CompetitivePriceType[] competitivePricesField;
    
    private OfferListingCountType[] numberOfOfferListingsField;
    
    private MoneyType tradeInValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CompetitivePrice", IsNullable=false)]
    public CompetitivePriceType[] CompetitivePrices {
        get {
            return this.competitivePricesField;
        }
        set {
            this.competitivePricesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OfferListingCount", IsNullable=false)]
    public OfferListingCountType[] NumberOfOfferListings {
        get {
            return this.numberOfOfferListingsField;
        }
        set {
            this.numberOfOfferListingsField = value;
        }
    }
    
    /// <remarks/>
    public MoneyType TradeInValue {
        get {
            return this.tradeInValueField;
        }
        set {
            this.tradeInValueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VariationParentType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class BaseRelationshipType {
    
    private IdentifierType identifiersField;
    
    /// <remarks/>
    public IdentifierType Identifiers {
        get {
            return this.identifiersField;
        }
        set {
            this.identifiersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class AttributeSetType {
    
    private object nilField;
    
    /// <remarks/>
    public object nil {
        get {
            return this.nilField;
        }
        set {
            this.nilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
public partial class SellerSKUIdentifier {
    
    private string marketplaceIdField;
    
    private string sellerIdField;
    
    private string sellerSKUField;
    
    /// <remarks/>
    public string MarketplaceId {
        get {
            return this.marketplaceIdField;
        }
        set {
            this.marketplaceIdField = value;
        }
    }
    
    /// <remarks/>
    public string SellerId {
        get {
            return this.sellerIdField;
        }
        set {
            this.sellerIdField = value;
        }
    }
    
    /// <remarks/>
    public string SellerSKU {
        get {
            return this.sellerSKUField;
        }
        set {
            this.sellerSKUField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01")]
[System.Xml.Serialization.XmlRootAttribute("VariationParent", Namespace="http://mws.amazonservices.com/schema/Products/2011-10-01", IsNullable=false)]
public partial class VariationParentType : BaseRelationshipType {
}
